### ISSUE TITLE
Enumerating shares on a host

### ISSUE THREAD

**Issue by elad** [bchelli/node-smb2#21]
Hello,

Is it possible to use this module to enumerate shares on a host? Or for getting the NetBIOS name of a host by its IP?

Thanks!

**Comment by hkmoon** [comment]
Hi, 

Thank you for the great project!
Could we have all the shares on a host easily as @elad mentioned above?

Thanks!

**Comment by bchelli** [comment]
Hi @elad 
This is supposed to be a library that mimic the fs standard library from node, therefore, there is no plan to support this type of feature.
That being said, if you want to contribute and open a pull request to add this feature, feel free to do so.
Thanks,
