### ISSUE TITLE
browserify module

### ISSUE THREAD

**Issue by Jomme5** [bchelli/node-smb2#22]
Is it possible to browserify the module or make it nodejs independend so it can be used in hybrid apps on smartphone-devices?

**Comment by aarongodin** [comment]
What would you recommend to make this module "node independent"? It's a library that leverages the standard library in node.

**Comment by bchelli** [comment]
Hi @Jomme5 
No plan to support browserify in the pipeline, if you want to open a pull request, you are very welcome to do so.
Thanks,
