### ISSUE TITLE
Module Not Working

### ISSUE THREAD

**Issue by humming-bird** [bchelli/node-smb2#4]
I cannot get this module to connect to my samba server using the code as advised in the documentation:
# CODE

// load the library 

```
var SMB2 = require('smb2');

// create an SMB2 instance 
var smb2Client = new SMB2({share: "\\\\192.168.1.6\\media",
    domain: '',
    username: 'user_not_shown',
    password: 'real_passworn_not_shown',
     debug: true,
    autoCloseTimeout: 0
});


smb2Client.readdir('Docos\\SMB_Test\\Adult', function(err, data){
    if(err) {
        console.log("Error (readdir):\n", err);
        console.log("data", data);
    } else {
        console.log("Connection made.");
        console.log(data); 
    }
});
```
# RESPONSE

--request
fe534d42400000000000000000007e0000000000000000000000000000000000d2e24ba20000000000000000000000000000000000000000000000000000000024000200010000000000000000000000000000000000000000000000000000000000000002021002

Please assist.
This is my first post - apologies if the format or content is ambiguous/unclear.

**Comment by bchelli** [comment]
Hi @humming-bird ,

Sorry for the late response.

Did you specify a domain in your code?
If not the domain is mandatory to connect to an SMB server.

Thanks,

**Comment by humming-bird** [comment]
Hi bchelli,

Many thanks for your response.
I confirm that the 'Domain' was left blank - I do not  belong to a domain, but a workgroup.

Python's implementation of smb (pysmb) can be used without setting a domain. How can I use your module for a workgroup - my computers are all on the same subnet and I do not have a requirement for a domain?

Thanks.

**Comment by bchelli** [comment]
Hi @humming-bird,

The workgroup is actually the domain – [explanation here](https://lists.samba.org/archive/samba/2005-July/108302.html).
Could you try specifying your workgroup in the domain parameter?

Thanks

**Comment by humming-bird** [comment]
Hi bchelli,

I have verified that my workgroup is called  'WORKGROUP'.
The code has been edited using 'WORKGROUP' as the domain. The result is the same. 
```
var smb2Client = new SMB2({share: "\\\\192.168.1.6\\media",
      domain: 'WORKGROUP',
      username: 'user_not_shown',
      password: 'real_passworn_not_shown',
       debug: true,
      autoCloseTimeout: 0
});
```
Both mac and Windows 7 produce the same error. 

Thanks

**Comment by simonhochrein** [comment]
This issue is the same on a mac
access token but no methods are working
```
 // load the library 
var SMB2 = require('smb2');
 
// create an SMB2 instance 
var smb2Client = new SMB2({
  share:'\\\\192.168.1.SOMENUMBER\\cloudshare'
, domain:'WORKGROUP'
, username:'guest'
, password:'',
    debug:true
});

smb2Client.exists('Data', function (err, exists) {
    if (err) throw err;
    console.log(exists ? "it's there" : "it's not there!");
});```

**Comment by liscmiracle** [comment]
Hi @humming-bird ,
maybe you run your code in main process, you can try run it in browser process.

**Comment by bchelli** [comment]
dead thread, closing the issue
