### ISSUE TITLE
more information with readdir?

### ISSUE THREAD

**Issue by sirber** [bchelli/node-smb2#5]
Hi,

I would like to have more information about files and folders, like the timestamps, if it's a file or folder, etc.

Thank you!

**Comment by sirber** [comment]
I found in the sources:
lib/api/readdir.js
.map(function(v){ return v.Filename }) // get the filename only

I'll experiment a bit with it.

**Comment by bchelli** [comment]
Hi @sirber,

This method need to keep the same signature than the [one provided in nodejs](https://nodejs.org/api/fs.html#fs_fs_readdir_path_callback)

What you are looking for is the implementation of [fs.stat](https://nodejs.org/api/fs.html#fs_fs_stat_path_callback)

This is not yet done, feel free to write it :smiley: and to create a pull request.

Thanks

**Comment by sirber** [comment]
Hi,
I'll look into it!

--
Stéphane Bérubé


Date: Sat, 23 May 2015 12:01:20 -0700
