### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by jrbecart** [bchelli/node-smb2#8]
I got an error using smb2: ECONNRESET

Here is the end of the log

```
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
-- error
{ '0': { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
```

My config is:

```
var smb2Client = new SMB2({
      share:'\\\\MYHOSTNAME\\MYSHARE'
    , domain:'MYDOMAIN'
    , username:'MYUN'
    , password:'MYPWD'
    , debug: true
        , autoCloseTimeout: 0
});
```

Any idea where to start looking?

PS: My folder have more than 20000 files.

**Comment by ooskapenaar** [comment]
We are routinely running into this problem too, and are currently looking into why some servers respond and others do not, although there are no noticeable differences in the server setup.

**Comment by marsaud** [comment]
When using `readdir` several times on the same folder : 
- I read successfully on first attempt.
- Second attempt throws a 'write after end' error
- All subsequent attempts throw ECONNRESET

If I close the client and instanciate a new one on the same share, in the same process, this cycle is reproduced from the beginning.

**Comment by marsaud** [comment]
This may be solved by #12

**Comment by marsaud** [comment]
@jrbecart, @ooskapenaar does your problems persist with 0.2.7 ?

**Comment by ooskapenaar** [comment]
@marsaud will test and get back to you asap.  Haven't used the functionality for a while.

**Comment by jrbecart** [comment]
@marsaud I did a few tests and it seems to be ok. Thanks.

**Comment by rdewolff** [comment]
Still having this issue.

**Comment by desmondnzuza** [comment]
Experiencing the same issue. I'm on 0.2.7.

Any update on this?

**Comment by bchelli** [comment]
Can you try with the latest version v0.2.9?

**Comment by bchelli** [comment]
Can you try with the latest version v0.2.11?
