### ISSUE TITLE
CreateReadStream and CreateWriteStream

### ISSUE THREAD

**Issue by marsaud** [bchelli/node-smb2#9]
Hi,

The ability to stream through your client would be great, and usefull.

**Comment by bchelli** [comment]
Hey @marsaud,

Yep I know this is a feature in my TODO list, but I don't have much time to work on that...
If you feel like it, create a pull request.

Thanks,

**Comment by marsaud** [comment]
Hi @bchelli,

I'm working on it, along with other things following my today needs with smb protocol. So I don't feel my fork is suitable pour a PR in your repository yet, but I'll create the PR anyway so you or other users can have a glimpse on it.

**Comment by bchelli** [comment]
Hi @marsaud,
Long time no see ;)
Do you want to merge your repo with this version of SMB2 or do you want to keep it as a forked version?
Cheers,
